services:
  closings-app:
    image: trawen/closings-app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    env_file:
      - .env.docker

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod", "-U", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 8
    volumes:
      - db_data:/data/db

  nginx:
    image: nginx
    restart: always
    depends_on: 
      - closings-app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:r

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: echo "Certbot intialized, waiting for external commands..."

volumes:
  db_data:
  shared_nginx_conf: